import type { PublicTrace } from '../server/actions/decision-trace';

// Render the customer-facing decision trace as a standalone HTML page. The
// page is intentionally minimal: every detail comes from server-side data we
// already store, every block is sanitized, and there is no JavaScript. The
// goal is "auditor friendly" — open the link, see exactly why the AI said
// what it said, screenshot for compliance.

const ESCAPE_MAP: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (ch) => ESCAPE_MAP[ch] ?? ch);
}

export function renderTracePage(trace: PublicTrace): string {
  const sources = trace.kbSources
    .map((s) => {
      const refreshed = s.last_refreshed_at
        ? `<span class="muted"> refreshed ${formatDate(s.last_refreshed_at)}</span>`
        : '';
      const title = escapeHtml(s.title);
      const inner = s.url
        ? `<a href="${escapeHtml(s.url)}" target="_blank" rel="noopener noreferrer">${title}</a>`
        : title;
      return `<li>${inner}${refreshed}</li>`;
    })
    .join('');

  const calls = trace.mcpCalls
    .map((call) => {
      const tag = call.read_only ? 'read' : 'write';
      const approver = call.approved_by_human ? ' · operator-approved' : '';
      return `<li><code>${escapeHtml(call.label)}</code> <span class="muted">(${tag}, ${escapeHtml(
        call.status,
      )}${approver})</span></li>`;
    })
    .join('');

  const procLine = trace.procedure
    ? `<dt>Procedure</dt><dd>${escapeHtml(trace.procedure.name)} <span class="muted">v${escapeHtml(
        trace.procedure.version,
      )}</span></dd>`
    : '';

  const confidence =
    trace.confidence !== null
      ? `<dt>Confidence</dt><dd>${(trace.confidence * 100).toFixed(0)}%</dd>`
      : '';
  const evalLine =
    trace.evalPassRate !== null
      ? `<dt>Procedure eval pass rate</dt><dd>${(trace.evalPassRate * 100).toFixed(
          0,
        )}% on the workspace's historical cases</dd>`
      : '';
  const approver = trace.approver
    ? `<dt>Approver</dt><dd>${escapeHtml(trace.approver)}</dd>`
    : '';

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Why this answer? — ${escapeHtml(trace.workspaceLabel)}</title>
  <style>
    :root { color-scheme: light dark; }
    body { font-family: ui-sans-serif, system-ui, sans-serif; max-width: 720px; margin: 40px auto; padding: 0 24px; line-height: 1.5; color: #0f172a; }
    @media (prefers-color-scheme: dark) { body { color: #e2e8f0; background: #0f172a; } a { color: #93c5fd; } }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .muted { color: #64748b; font-size: 13px; }
    dt { font-weight: 600; margin-top: 12px; font-size: 13px; text-transform: uppercase; letter-spacing: 0.04em; color: #475569; }
    dd { margin: 4px 0 0 0; padding: 0; }
    ul { padding-left: 18px; }
    code { background: rgba(100,116,139,0.15); padding: 1px 6px; border-radius: 3px; font-size: 13px; }
    section { margin-top: 20px; }
    .reason { background: rgba(56,189,248,0.08); border-left: 3px solid #38bdf8; padding: 12px 14px; border-radius: 4px; }
  </style>
</head>
<body>
  <h1>Why this answer?</h1>
  <div class="muted">${escapeHtml(trace.workspaceLabel)} · ${escapeHtml(trace.channel)} · ${formatDate(
    trace.authoredAt,
  )}</div>
  <section class="reason">${escapeHtml(trace.reasonSummary)}</section>
  <dl>
    ${procLine}
    ${confidence}
    ${evalLine}
    ${approver}
  </dl>
  ${sources ? `<section><h2>Knowledge cited</h2><ul>${sources}</ul></section>` : ''}
  ${calls ? `<section><h2>Actions taken</h2><ul>${calls}</ul></section>` : ''}
  <section class="muted" style="margin-top:32px;font-size:12px">
    This page shows the decision trace for an AI-generated reply on your support ticket.
    Generated by <a href="https://getranse.com" target="_blank" rel="noopener noreferrer">Ranse</a>.
  </section>
</body>
</html>`;
}

function formatDate(timestamp: number): string {
  return `${new Date(timestamp).toISOString().replace('T', ' ').slice(0, 16)}Z`;
}
