import { Hono } from 'hono';
import { registerApprovalRoutes } from './approvals';
import { registerBillingRoutes } from './billing';
import { registerChannelRoutes } from './channels';
import { type Ctx, installApiAuth } from './context';
import { registerEvalRoutes } from './evals';
import { registerInsightRoutes } from './insights';
import { registerKnowledgeRoutes } from './knowledge';
import { registerLlmRoutes } from './llm';
import { registerMcpRoutes } from './mcp';
import { registerMemoryRoutes } from './memory';
import { registerNotificationRoutes } from './notifications';
import { registerOnboardingRoutes } from './onboarding';
import { registerProcedureRoutes } from './procedures';
import { registerSearchRoutes } from './search';
import { registerSettingsRoutes } from './settings';
import { registerTicketRoutes } from './tickets';
import { registerWorkspaceRoutes } from './workspaces';

export const apiApp = new Hono<Ctx>();

installApiAuth(apiApp);
registerTicketRoutes(apiApp);
registerSearchRoutes(apiApp);
registerChannelRoutes(apiApp);
registerSettingsRoutes(apiApp);
registerNotificationRoutes(apiApp);
registerApprovalRoutes(apiApp);
registerKnowledgeRoutes(apiApp);
registerMemoryRoutes(apiApp);
registerProcedureRoutes(apiApp);
registerMcpRoutes(apiApp);
registerLlmRoutes(apiApp);
registerEvalRoutes(apiApp);
registerInsightRoutes(apiApp);
registerBillingRoutes(apiApp);
registerOnboardingRoutes(apiApp);
registerWorkspaceRoutes(apiApp);
