import { Hono } from 'hono';
import { registerApprovalRoutes } from './approvals';
import { registerBillingRoutes } from './billing';
import { registerChannelRoutes } from './channels';
import { type Ctx, installApiAuth } from './context';
import { registerEvalRoutes } from './evals';
import { registerInsightRoutes } from './insights';
import { registerKnowledgeRoutes } from './knowledge';
import { registerKnowledgePublicRoutes } from './knowledge-public';
import { registerLlmRoutes } from './llm';
import { registerMcpRoutes } from './mcp';
import { registerMemoryRoutes } from './memory';
import { registerNotificationRoutes } from './notifications';
import { registerOnboardingRoutes } from './onboarding';
import { registerProcedureRoutes } from './procedures';
import { registerTicketRoutes } from './tickets';
import { registerMacroRoutes } from './tickets/macros';
import { registerMergeRoutes } from './tickets/merge';
import { registerSearchRoutes } from './tickets/search';
import { registerTagRoutes } from './tickets/tags';
import { registerWorkspaceRoutes } from './workspaces';
import { registerIntegrationRoutes } from './workspaces/integrations';
import { registerSettingsRoutes } from './workspaces/settings';
import { registerTeamRoutes } from './workspaces/teams';

export const apiApp = new Hono<Ctx>();

installApiAuth(apiApp);
registerTicketRoutes(apiApp);
registerSearchRoutes(apiApp);
registerTagRoutes(apiApp);
registerIntegrationRoutes(apiApp);
registerMacroRoutes(apiApp);
registerMergeRoutes(apiApp);
registerTeamRoutes(apiApp);
registerChannelRoutes(apiApp);
registerSettingsRoutes(apiApp);
registerNotificationRoutes(apiApp);
registerApprovalRoutes(apiApp);
registerKnowledgeRoutes(apiApp);
registerKnowledgePublicRoutes(apiApp);
registerMemoryRoutes(apiApp);
registerProcedureRoutes(apiApp);
registerMcpRoutes(apiApp);
registerLlmRoutes(apiApp);
registerEvalRoutes(apiApp);
registerInsightRoutes(apiApp);
registerBillingRoutes(apiApp);
registerOnboardingRoutes(apiApp);
registerWorkspaceRoutes(apiApp);
