// Enforces Conventional Commits v1.0.0 (see CLAUDE.md "Commit messages").
export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      1,
      'always',
      [
        'inbox',
        'agents',
        'channels',
        'email',
        'notifications',
        'knowledge',
        'memory',
        'mcp',
        'procedures',
        'evals',
        'workspaces',
        'onboarding',
        'insights',
        'outcomes',
        'billing',
        'auth',
        'audit',
        'approvals',
        'jobs',
        'http',
        'api',
        'ui',
        'llm',
        'db',
        'setup',
        'deploy',
        'scripts',
        'security',
        'ci',
        'docs',
        'deps',
        'test',
        'release',
      ],
    ],
  },
};
