import type { EmailFeedbackLinks } from '../../../interfaces/replies';

export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export function appendPlainTextFeedback(
  text: string,
  feedback?: EmailFeedbackLinks | null,
): string {
  if (!feedback) return text;
  return `${text.trimEnd()}\n\nWas this helpful?\nYes: ${feedback.positive}\nNo: ${feedback.negative}`;
}

// Customers must always be able to tell an AI reply from a human one (the
// Air Canada / Cursor incidents both hinged on undisclosed bots), so the
// disclosure renders whenever no human authored the reply — with or without
// a working trace link.
export function appendPlainTextTrace(
  text: string,
  traceUrl?: string | null,
  aiAuthored?: boolean,
): string {
  if (!aiAuthored && !traceUrl) return text;
  const notice = aiAuthored ? 'This reply was generated by AI.' : null;
  const trace = traceUrl ? `Why this answer? ${traceUrl}` : null;
  return `${text.trimEnd()}\n\n${[notice, trace].filter(Boolean).join(' ')}`;
}

export function traceHtml(traceUrl?: string | null, aiAuthored?: boolean): string {
  if (!aiAuthored && !traceUrl) return '';
  const notice = aiAuthored ? 'This reply was generated by AI. ' : '';
  const link = traceUrl
    ? `<a href="${escapeHtml(traceUrl)}" style="color:#64748b;text-decoration:underline;">Why this answer?</a>`
    : '';
  return `<div style="margin-top:8px;color:#64748b;font-size:12px;">${notice}${link}</div>`;
}

export function feedbackHtml(feedback?: EmailFeedbackLinks | null): string {
  if (!feedback) return '';
  return `<div style="margin-top:32px;padding-top:14px;border-top:1px solid #eee;color:#555;font-size:13px;">Was this helpful? <a href="${escapeHtml(feedback.positive)}" style="display:inline-block;margin-left:8px;color:#0f766e;text-decoration:none;">Yes</a> <a href="${escapeHtml(feedback.negative)}" style="display:inline-block;margin-left:8px;color:#991b1b;text-decoration:none;">No</a></div>`;
}
