import { describe, expect, it } from 'vitest';
import {
  buildHtmlWithSignature,
  buildPlainTextWithSignature,
} from '../src/server/inbox/email/html';

const ctx = { workspaceName: 'Acme Support', fromName: 'Acme' };

describe('AI disclosure on outbound replies', () => {
  it('labels AI-authored replies in both plain text and HTML', async () => {
    const text = buildPlainTextWithSignature(
      'Your refund is on its way.',
      { ...ctx, aiAuthored: true },
      null,
      null,
    );
    expect(text).toContain('This reply was generated by AI.');

    const html = await buildHtmlWithSignature(
      'Your refund is on its way.',
      { ...ctx, aiAuthored: true },
      null,
      null,
    );
    expect(html).toContain('This reply was generated by AI.');
  });

  it('discloses even when the trace link is missing, and links the trace when present', async () => {
    const noTrace = buildPlainTextWithSignature('Hi', { ...ctx, aiAuthored: true }, null, null);
    expect(noTrace).toContain('This reply was generated by AI.');
    expect(noTrace).not.toContain('Why this answer?');

    const withTrace = buildPlainTextWithSignature(
      'Hi',
      { ...ctx, aiAuthored: true },
      null,
      'https://acme.example/public/trace/tok',
    );
    expect(withTrace).toContain('This reply was generated by AI.');
    expect(withTrace).toContain('Why this answer? https://acme.example/public/trace/tok');
  });

  it('never labels human-authored replies', async () => {
    const text = buildPlainTextWithSignature('Hello from a human', ctx, null, null);
    expect(text).not.toContain('generated by AI');

    const html = await buildHtmlWithSignature('Hello from a human', ctx, null, null);
    expect(html).not.toContain('generated by AI');
  });
});
