import type { FirstPartyMcpTemplate } from '../../../../interfaces/mcp';
export type { FirstPartyMcpTemplate };


export const FIRST_PARTY_MCP_TEMPLATES: FirstPartyMcpTemplate[] = [
  {
    id: 'stripe',
    name: 'stripe',
    label: 'Stripe',
    description: 'Billing lookup and refund actions exposed through a Stripe MCP server.',
    expectedTools: ['customers.search', 'subscriptions.retrieve', 'refunds.create'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-stripe-mcp.example.com/mcp',
  },
  {
    id: 'shopify',
    name: 'shopify',
    label: 'Shopify',
    description: 'Order lookup, fulfillment status, address edits, and return workflow actions.',
    expectedTools: ['orders.search', 'orders.retrieve', 'orders.update_address', 'returns.create'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-shopify-mcp.example.com/mcp',
  },
  {
    id: 'recharge',
    name: 'recharge',
    label: 'Recharge',
    description:
      'Subscription lookup, pause, and cancellation actions for Recharge-powered stores.',
    expectedTools: ['subscriptions.retrieve', 'subscriptions.pause', 'subscriptions.cancel'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-recharge-mcp.example.com/mcp',
  },
  {
    id: 'salesforce',
    name: 'salesforce',
    label: 'Salesforce',
    description: 'Contact lookup and case creation for enterprise escalations.',
    expectedTools: ['contacts.retrieve', 'cases.create'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-salesforce-mcp.example.com/mcp',
  },
  {
    id: 'hubspot',
    name: 'hubspot',
    label: 'HubSpot',
    description: 'Contact search and deal lookup so support inherits CRM context.',
    expectedTools: ['contacts.search', 'deals.retrieve'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-hubspot-mcp.example.com/mcp',
  },
  {
    id: 'linear',
    name: 'linear',
    label: 'Linear',
    description: 'Support escalations mapped to Linear issues and team workflows.',
    expectedTools: ['issues.create', 'issues.update', 'teams.list'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-linear-mcp.example.com/mcp',
  },
  {
    id: 'github',
    name: 'github',
    label: 'GitHub',
    description: 'Repository issue, pull request, and escalation actions through MCP.',
    expectedTools: ['issues.create', 'issues.comment', 'pull_requests.get'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-github-mcp.example.com/mcp',
  },
  {
    id: 'pagerduty',
    name: 'pagerduty',
    label: 'PagerDuty',
    description: 'Page on-call engineering when a customer report confirms an outage.',
    expectedTools: ['incidents.create'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-pagerduty-mcp.example.com/mcp',
  },
  {
    id: 'jira',
    name: 'jira',
    label: 'Jira',
    description: 'Search and create Jira issues for bug escalations.',
    expectedTools: ['issues.search', 'issues.create'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-jira-mcp.example.com/mcp',
  },
  {
    id: 'zendesk-import',
    name: 'zendesk',
    label: 'Zendesk import',
    description: 'Read-only Zendesk export to seed Ranse historical evals during migration.',
    expectedTools: ['tickets.list'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-zendesk-mcp.example.com/mcp',
  },
  {
    id: 'klaviyo',
    name: 'klaviyo',
    label: 'Klaviyo',
    description: 'Marketing-suppression and profile lookup for unsubscribe confirmations.',
    expectedTools: ['profiles.search', 'profiles.suppress'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-klaviyo-mcp.example.com/mcp',
  },
  {
    id: 'twilio-verify',
    name: 'twilio-verify',
    label: 'Twilio Verify',
    description: 'OTP delivery for identity-proof procedures on phone channels.',
    expectedTools: ['verifications.create'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-twilio-verify-mcp.example.com/mcp',
  },
  {
    id: 'auth0',
    name: 'auth0',
    label: 'Auth0',
    description: 'User search and password-change ticket issuance for account-recovery flows.',
    expectedTools: ['users.search', 'tickets.password_change'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-auth0-mcp.example.com/mcp',
  },
  {
    id: 'notion',
    name: 'notion',
    label: 'Notion',
    description: 'Pull runbook pages or hand off structured summaries to the docs team.',
    expectedTools: ['databases.query', 'pages.create'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-notion-mcp.example.com/mcp',
  },
  {
    id: 'datadog',
    name: 'datadog',
    label: 'Datadog',
    description: 'Cross-post a customer-reported incident as a Datadog event.',
    expectedTools: ['events.create'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-datadog-mcp.example.com/mcp',
  },
  {
    id: 'snowflake',
    name: 'snowflake',
    label: 'Snowflake',
    description: 'Run a read-only analytics query for account usage / billing rows.',
    expectedTools: ['query.execute'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-snowflake-mcp.example.com/mcp',
  },
  {
    id: 'mixpanel',
    name: 'mixpanel',
    label: 'Mixpanel',
    description: 'Surface recent product-usage events to enrich a support reply.',
    expectedTools: ['events.query'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-mixpanel-mcp.example.com/mcp',
  },
  {
    id: 'slack',
    name: 'slack',
    label: 'Slack',
    description: 'Bridge support into shared customer Slack channels for escalations.',
    expectedTools: ['conversations.history', 'chat.post_message'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-slack-mcp.example.com/mcp',
  },
  {
    id: 'calendly',
    name: 'calendly',
    label: 'Calendly',
    description: 'Look up the customer upcoming bookings for meeting-context replies.',
    expectedTools: ['scheduled_events.list'],
    authType: 'bearer',
    endpointPlaceholder: 'https://your-calendly-mcp.example.com/mcp',
  },
  {
    id: 'generic-webhook',
    name: 'webhook',
    label: 'Generic webhook',
    description: 'A minimal MCP facade for internal HTTP actions owned by the workspace.',
    expectedTools: ['webhook.call'],
    authType: 'header',
    authHeaderName: 'x-ranse-webhook-secret',
    endpointPlaceholder: 'https://your-webhook-mcp.example.com/mcp',
  },
];
